<div class="row">
	<div class="col-md-4">
		<h3> Sửa thành viên</h3>
		<p>Vui lòng nhập đầy đủ thông tin bên dưới</p>
		<?php
			$form=$this->form;
			$form->prepare();
			$form->setAttribute('action',$this->url('training/member',array('action'=>'edit','id'=>$this->userid)));
			echo $this->form()->openTag($form);
			echo "<div class='form-group'>";
			echo $this->formLabel($form->get('level'));
			echo $this->formElement($form->get('level'));
			echo "</div>";
			echo "<div class='form-group'>";
			echo $this->formLabel($form->get('username'));
			echo $this->formElement($form->get('username'));
			echo $this->formElementErrors($form->get('username'));			
			echo "</div>";		
			echo "<div class='form-group'>";
			echo $this->formLabel($form->get('email'));
			echo $this->formElement($form->get('email'));
			echo $this->formElementErrors($form->get('email'));			
			echo "</div>";		
			echo "<div class='form-group'>";
			echo $this->formLabel($form->get('password'));
			echo $this->formElement($form->get('password'));
			echo $this->formElementErrors($form->get('password'));			
			echo "</div>";		
			echo "<div class='form-group'>";
			echo $this->formLabel($form->get('repassword'));
			echo $this->formElement($form->get('repassword'));
			echo $this->formElementErrors($form->get('repassword'));			
			echo "</div>";		
			echo "<div class='form-group'>";
			echo $this->formLabel($form->get('name'));
			echo $this->formElement($form->get('name'));
			echo $this->formElementErrors($form->get('name'));			
			echo "</div>";	
			echo $this->formElement($form->get('submit'));													
			echo $this->form()->closeTag();

		?>
	</div>
</div>