<div class="row">
	<div class="col-md-4">
		<h3> Đăng nhập </h3>
		<p>Vui lòng nhập đầy đủ thông tin bên dưới</p>
		<?php
			if($this->error != ""){
				echo "<div class='alert alert-danger'>";
				echo $this->error;
				echo "</div>";
			}
			if(count($this->flash)){
				echo "<div class='alert alert-success'>";
				foreach($this->flash as $mess){
					echo $mess;
				}
				echo "</div>";
			}

			$form=$this->form;
			$form->prepare();
			$form->setAttribute('action',$this->url('blog/auth',array('action'=>'login')));
			echo $this->form()->openTag($form);
			echo "<div class='form-group'>";
			echo $this->formLabel($form->get('username'));
			echo $this->formElement($form->get('username'));
			echo $this->formElementErrors($form->get('username'));			
			echo "</div>";		
		
			echo "<div class='form-group'>";
			echo $this->formLabel($form->get('password'));
			echo $this->formElement($form->get('password'));
			echo $this->formElementErrors($form->get('password'));			
			echo "</div>";	
	

			echo $this->formElement($form->get('submit'));													
			echo $this->form()->closeTag();

		?>
	</div>
</div>