<div class="row">
	<div class="col-md-4">
		<h3> Lấy lại mật khẩu </h3>
		<p>Vui lòng nhập email của bạn, để hệ thống gởi liên kết phục hồi mật khẩu </p>
		<?php
			if($this->error != ""){
				echo "<div class='alert alert-danger'>";
				echo $this->error;
				echo "</div>";
			}
			if($this->mess != ""){
				echo "<div class='alert alert-success'>";
				echo $this->mess;
				echo "</div>";
			}			
			$form=$this->form;
			$form->prepare();
			$form->setAttribute('action',$this->url('training/verify',array('action'=>'forgot')));
			echo $this->form()->openTag($form);
			echo "<div class='form-group'>";
			echo $this->formLabel($form->get('email'));
			echo $this->formElement($form->get('email'));
			echo $this->formElementErrors($form->get('email'));			
			echo "</div>";		

			echo $this->captcha->getHTML();
	

			echo $this->formElement($form->get('submit'));													
			echo $this->form()->closeTag();

		?>

	</div>
</div>