<div class="row">
	<div class="col-md-4">
		<h3> Chỉnh sửa tập tin </h3>
		<p> Bạn có thể chỉnh sửa lại tên tập tin </p>
		<?php

			$form=$this->form;
			$form->prepare();
			$form->setAttribute('action',$this->url('training/file',array('action'=>'edit','id'=>$this->fileId)));
			echo $this->form()->openTag($form);
			echo "<div class='form-group'>";
			echo $this->formLabel($form->get('label'));
			echo $this->formElement($form->get('label'));
			echo $this->formElementErrors($form->get('label'));			
			echo "</div>";		
	
	

			echo $this->formElement($form->get('submit'));													
			echo $this->form()->closeTag();

		?>

	</div>
</div>