<div class="row">
	<div class="col-md-9">
		<h2> Giỏ hàng </h2>
		<p><a href="<?php echo $this->url('training/book'); ?>"> Mua sản phẩm khác </a> / <b><?php echo $this->count;?></b> Sản phẩm trong giỏ hàng</p>
		<?php
			if(count($flash)){
				echo "<div class='alert alert-success'>";
				echo $flash[0];
				echo "</div>";
			}		
			$form=$this->form;
			$form->prepare();
			$form->setAttribute('action',$this->url('training/book',array('action'=>'updateItem')));
			$form->setAttribute('method','POST');
			echo $this->form()->openTag($form);
		?>
		<table class="table" width="500">
			<tr>
				<td>Tên sản phẩm</td>
				<td>Số lượng</td>
				<td> Giá tiền</td>
				<td> Xóa bỏ </td>
			</tr>
			<?php
				if($this->count != 0){
					foreach($this->books as $token=>$book){
						echo $this->formElement($form->get($book['id']."[token]"));
						echo "<tr>";
						echo "<td>$book[name]</td>";
						echo "<td>".$this->formElement($form->get($book['id']."[qty]"))."</td>";
						echo "<td>".$book['qty']*$book['price']."</td>";
						echo "<td><a href='".$this->url('training/book',array('action'=>'removeItem','id'=>$book['id']))."' class='btn btn-danger'> Xóa</a></td>";
						echo "</tr>";
					}
					echo "<tr>";
					echo "<td colspan='2'>Tổng tiền</td>";
					echo "<td colspan='2'>".$this->total['sub-total']."</td>";
					echo "</tr>";
				}else{
					echo "<tr>";
					echo "<td colspan='4'> Không có sản phẩm nào trong giỏ hàng. Hãy mua hàng <a href='".$this->url('training/book')."'>tại đây</a></td>";
					echo "</tr>";
				}
			?>
		<table>
		<?php
			echo $this->formElement($form->get('submit'));
			echo "&nbsp;<a href='".$this->url('training/book',array('action'=>'removeAll'))."' class='btn btn-danger'>Xóa toàn bộ</a>";		
			echo "&nbsp;<a href='".$this->url('training/book',array('action'=>'checkout'))."' class='btn btn-success'> Thanh toán</a>";				
			echo $this->form()->closeTag();
		?>
	</div>
</div>