<div class='row'>
	<div class='col-md-7'>
		<h3>Lịch sử mua hàng</h3>
		<?php
			if(count($flash)){
				echo "<div class='alert alert-success'>";
				echo $flash[0];
				echo "</div>";
			}
		?>
		<table class='table' width='500'>
			<tr>
				<td> ID </td>
				<td> Thời gian </td>
				<td> Tổng tiền</td>
				<td> Xem chi tiết</td>
			</tr>
			<?php
				if(count($this->orders)){
					foreach ($this->orders as $order) {
						echo "<tr>";
						echo "<td> $order->id </td>";
						echo "<td> $order->stamp</td>";
						echo "<td> $order->total</td>";
						echo "<td><a href='".$this->url('training/book',array('action'=>'viewOrder','id'=>$order->id))."'> Chi tiết </a></td>";
						echo "</tr>";
					}
				}else{
					echo "<tr>";
					echo "<td colspan='4' align='center'> Bạn chưa mua sản phẩm nào. Hãy mua hàng <a href='".$this->url('training/book')."'>Tại đây</a></td>";
					echo "</tr>";
				}
			?>
		</table>
	</div>
</div>