<div class='row'>
	<div class='col-md-7'>
		<h3> Xác nhận hoàn tất thanh toán </h3>
		<p>Cảm ơn bạn đã mua hàng của chúng tôi. Bên dưới là thông tin hóa đơn của bạn về sản phẩm đã mua</p>
		<table width='50%' border='1'>
			<tr>
				<td>
					<b>Mã hóa đơn: </b> QHOBOOK-<?php echo $this->payment['orderId'];?><br />
					<b>Tình trạng:</b> Đã thanh toán<br />
					<b>Ngày thanh toán:</b> <?php echo $this->payment['time'];?>
					<b>Hình thức thanh toán:</b> Paypal
				</td>
			</tr>
		</table>
		<br />
		<table width='50%' border='1'>
			<tr>
				<td>
					<h4>Thông tin giao hàng</h4>
				</td>
			</tr>
			<tr>
				<td>
					<?php echo $this->payment['ship_name'];?><br />
					<?php echo $this->payment['ship_address'];?><br />
					(Thời gian giao hang từ 5-->7 ngày làm việc)<br />
				</td>
			</tr>
		</table>
		<h4> Chi tiết sản phẩm</h4>
		<table width='80%' border='1'>
			<tr>
				<th> Tên sản phẩm</th>
				<th>Số lượng</th>
				<th>Giá tiền</th>
				<th>Thành tiền</th>
			</tr>
			<?php
				foreach($this->payment['detail'] as $id=>$item){
					echo "<tr>";
					echo "<td> $item[name]</td>";
					echo "<td>$item[qty]</td>";
					echo "<td>$item[price]</td>";
					echo "<td>".($item['price']*$item['qty'])."</td>";
					echo "</tr>";
				}

			?>
			<tr>
				<td colspan='3'>Tổng tiền</td>
				<td><?php echo $this->payment['total'];?></td>
			</tr>
		</table>
		<hr />
		<a href='javascript:void(0)' onClick='window.print();'>&raquo; In hóa đơn xác nhận này</a>
	</div>
</div>