<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;QHOnline Training</a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php
                        echo $this->navigation('member_navigation')->menu()->setAcl($this->acl)->setRole($this->role)->setMaxDepth(0)->setUlClass('nav navbar-nav');
                    ?>
                    <!--<ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li><a href="<?php echo $this->url('training/member') ?>">Member Manager</a></li>
                        <li><a href="<?php echo $this->url('training/book') ?>"> Book Store </a></li>       
                        <li><a href="<?php echo $this->url('training/file') ?>">File Manager</a></li>                                            
                        <li><a href="<?php echo $this->url('training/chat') ?>">Chat System</a></li>                        
                        <li><a href="<?php echo $this->url('training/verify',array('action'=>'logout')) ?>">Logout (<?php echo $this->layout()->username_layout; ?>)</a></li>                                                
                    </ul>-->
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php
                echo $this->navigation('member_navigation')->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->setPartial('training/layout/breadcrumbs.phtml');
            ?>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
