<div class="row">
	<div class="col-md-8">
		<h3> Danh sách các bài viết</h3>
		<?php
			if(count($this->flash)){
				$mess=$this->flash;
				echo "<div class='alert alert-success'>";
				echo $mess[0];
				echo "</div>";
			}
		?>
		<table class="table table-striped">
			<tr>
				<td> STT </td>
				<td> Tên bài viết</td>
				<td> Tình trạng</td>
				<td> Chuyên mục </td>
				<td> Sửa </td>
				<td> Xóa </td>
			</tr>
			<?php
			foreach($this->posts as $k=>$post){
				echo "<tr>";
				echo "<td>".($k+1)."</td>";
				echo "<td>".$post->getTitle()."</td>";
				if($post->getStatus() == 1){
					echo "<td><font color='red'>Chưa duyệt</font></td>";
				}else{
					echo "<td>Duyệt</td>";
				}
				echo "<td>".$post->getCate()->getName()."</td>";
				echo "<td><a href='".$this->url('blog/post',array('action'=>'edit','id'=>$post->getId()))."'> Sửa </a></td>";
				echo "<td><a href='".$this->url('blog/post',array('action'=>'del','id'=>$post->getId()))."'> Xóa </a></td>";
				echo "</tr>";
			}
			?>
		</table>
		<hr />
		<a href="<?php echo $this->url('blog/post',array('action'=>'add'));?>"> &raquo; Thêm bài viết mới </a>
	</div>
</div>